'package:cpu':
  - changed-files:
    - any-glob-to-any-file:
      - 'cpu/**'

'package:disk':
  - changed-files:
    - any-glob-to-any-file:
      - 'disk/**'

'package:docker':
  - changed-files:
    - any-glob-to-any-file:
      - 'docker/**'

'package:host':
  - changed-files:
    - any-glob-to-any-file:
      - 'host/**'

'package:load':
  - changed-files:
    - any-glob-to-any-file:
      - 'load/**'

'package:mem':
  - changed-files:
    - any-glob-to-any-file:
      - 'mem/**'

'package:net':
  - changed-files:
    - any-glob-to-any-file:
      - 'net/**'

'package:process':
  - changed-files:
    - any-glob-to-any-file:
      - 'process/**'

'package:sensors':
  - changed-files:
    - any-glob-to-any-file:
      - 'sensors/**'

'package:winservices':
  - changed-files:
    - any-glob-to-any-file:
      - 'winservices/**'

'os:linux':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*_linux.go'
      - '**/*_linux_mips64.go'
      - '**/*_linux_386.go'
      - '**/*_linux_test.go'
      - '**/*_linux_s390x.go'
      - '**/*_linux_amd64.go'
      - '**/*_linux_arm64.go'
      - '**/*_linux_arm.go'
      - '**/*_posix.go'

'os:freebsd':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*_freebsd.go'
      - '**/*_freebsd_386.go'
      - '**/*_freebsd_test.go'
      - '**/*_freebsd_amd64.go'
      - '**/*_freebsd_arm64.go'
      - '**/*_freebsd_arm.go'
      - '**/*_bsd.go'
      - '**/*_posix.go'

'os:darwin':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*_darwin.go'
      - '**/*_darwin_386.go'
      - '**/*_darwin_test.go'
      - '**/*_darwin_amd64.go'
      - '**/*_darwin_arm64.go'
      - '**/*_posix.go'

'os:openbsd':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*_openbsd.go'
      - '**/*_openbsd_386.go'
      - '**/*_openbsd_test.go'
      - '**/*_openbsd_amd64.go'
      - '**/*_openbsd_arm64.go'
      - '**/*_openbsd_arm.go'
      - '**/*_bsd.go'
      - '**/*_posix.go'

'os:windows':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*_windows.go'
      - '**/*_windows_386.go'
      - '**/*_windows_test.go'
      - '**/*_windows_amd64.go'
      - '**/*_windows_32bit.go'
      - '**/*_windows_64bit.go'

'os:solaris':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*_solaris.go'
      - '**/*_posix.go'