on: [push, pull_request]
name: Build Test
permissions:
  contents: read

jobs:
  build_test_v3:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - id: cache-paths
      run: |
        echo "::set-output name=cache::$(go env GOCACHE)"
        echo "::set-output name=mod-cache::$(go env GOMODCACHE)"
    - name: Cache go modules
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.cache-paths.outputs.cache }}
          ${{ steps.cache-paths.outputs.mod-cache }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Build Test v3
      run: |
        make build_test
