name: Release

on:
  schedule:
    - cron: '0 1 1 * *'  # UTC 01:00 on the first day of the Month

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Release
        run: make release
